### ISSUE TITLE
Any Official Repository on GitHub? :-(

### ISSUE THREAD

**Issue by reinhardjung** [ko31/star-cloudprnt-for-woocommerce-plus#5]
Hi Ko

Where can I find the GitHub Version of this PlugIn?
https://wordpress.org/plugins/star-cloudprnt-for-woocommerce/

This is not an official repository. Plugin page
https://github.com/antiproblemist/star-cloudprint-for-woocommerce
And this:
https://github.com/josedu90/star-cloudprnt-for-woocommerce

I’m totally confused on how to contribute
I do not think/hope - that there is only Version on WordPress SVN? ;-(

Thanx a lot for clarification...

**Comment by ko31** [comment]
Hi, @reinhardjung 

As far as I know, there is no official repository on GitHub yet.

I don't think the repositories you mentioned are official either.

I think they just currently maintain the latest code in their own repository.
https://wordpress.org/support/topic/version-2-0-upgrading-from-previous-releases/

I'm also hoping that code will be available on GitHub.

**Comment by reinhardjung** [comment]
Hi @ko31
Thanx a lot for your Feedback - helped me to clearify.

> As far as I know, there is no official repository on GitHub yet.
Yes, seems to be :-(

> I don't think the repositories you mentioned are official either.
Yes, seems to be :-(

I have found the Beta-Files to download:
But... :-(


> I think they just currently maintain the latest code in their own repository.
> https://wordpress.org/support/topic/version-2-0-upgrading-from-previous-releases/
> I'm also hoping that code will be available on GitHub.
Any Idea on how to change this?
4 Example: Who should we write to?

BTW:
What was your intention to create this "-plus" Version?
I mean instead of adding/forking the official release?
Do they don't want to? :-(

I loved to to see this, because of our "-plus"-Features.
But the "official" PlugIns now get some more Settings-Features.
Any Idea in how we should handle this?

BTW::2: 
I now created a new Repro on my GitLab to add a "PaperSaveMode".
But this should not be the right way, als well?
It should be in the official Release/Repro?

Need to:
- It also does not work in my local Mac
- More Language Support
- ...

**Comment by ko31** [comment]
Hi @reinhardjung 

> 4 Example: Who should we write to?

At the moment, the best way is to post your ideas in the support forum.
Then, the official developers will see it.
https://wordpress.org/support/plugin/star-cloudprnt-for-woocommerce/
 
> BTW:
> What was your intention to create this "-plus" Version?
> I mean instead of adding/forking the official release?
> Do they don't want to? :-(
> 
> I loved to to see this, because of our "-plus"-Features.
> But the "official" PlugIns now get some more Settings-Features.
> Any Idea in how we should handle this?

Actually, I created this repository for my own client work. 
For instance, I needed to support Japanese printing for my client.
I know official plugin has more new features, but I haven't been able to support it.
I'd really like to fork the official source code and add customization features to it, but I couldn't because the repository is not on GitHub.

> BTW::2:
> I now created a new Repro on my GitLab to add a "PaperSaveMode".
> But this should not be the right way, als well?
> It should be in the official Release/Repro?

I've heard that they are considering to create its official repository on GitHub.
When the time comes, I think we'll contribute it.

Thank you.

**Comment by Lozrus** [comment]
Hi @ko31 and @reinhardjung 

The good news is that we have already moved from our internal corporate version control servers to GitHub. Although it's a private repository now, my intention is to make it public very soon.

Honestly I'd hoped to do that sooner, but there are some internal company rules and paperwork (maybe Ko knows what Japanese companies can be like) which I must prepare first. It's totally down to me that this hasn't happened yet, as I can only spend a limited amount on time on this plugin between other projects and the support/feature requests have got my attention more.

I did spend some time last week on this though, the sooner we can make the repository public the better for me. I'd hope that I can get approval by the end of this week, or early next week.

**Comment by ko31** [comment]
@Lozrus 

Thank you for sharing the good news!

I guess it must have been a lot of work to prepare it, but I'm really looking forward to seeing it.

**Comment by Lozrus** [comment]
@ko31 and @reinhardjung 

Just for your information, the official repository is now public <https://github.com/star-micronics/star-cloudprnt-for-woocommerce>.

**Comment by ko31** [comment]
@Lozrus 
Congraturations! 🎉

**Comment by ko31** [comment]
@reinhardjung 
I'll close this issue.
Thank you.

**Comment by Lozrus** [comment]
@ko

> @Lozrus
> Congraturations! 🎉

Thank you, it was a nice opportunity to update the documentation and add the starting point of a developer guide. Hopefully that's helpful.
